#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          azure:
#            issuer-uri: https://login.microsoftonline.com/9cbb4e71-dd48-43a1-991f-379fe7fe47fb/v2.0
#        registration:
#          azure-dev:
#            provider: azure
#            client-id: 113d981b-832d-42b2-8c7b-2fd01a1df7a8
#            client-secret: r0W8Q~CV~FhB4VYj6BnsDwrN5x6m6yqKuO-2ndf.
#            scope:
#              - openid
#              - email
#              - profile


app:
  azure:
    AD:
      tenet-id: 9cbb4e71-dd48-43a1-991f-379fe7fe47fb
      client-id: 113d981b-832d-42b2-8c7b-2fd01a1df7a8
      client-secret: r0W8Q~CV~FhB4VYj6BnsDwrN5x6m6yqKuO-2ndf.
      token-uri: https://login.microsoftonline.com/9cbb4e71-dd48-43a1-991f-379fe7fe47fb/oauth2/v2.0/token